# This is a basic workflow to help you get started with Actions
name: action-demo
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: LiangRenDev/resuable-github-action-demo/.github/workflows/resuable.yml@feature/AddReusbale
    secrets: 
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}


