# This is a basic workflow to help you get started with Actions
name: action-demo
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_cd:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-cd
          path: ./cd

  build_dist_sub1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-dist-sub1
          path: ./dist/sub1
  build_dist_sub2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-dist-sub2
          path: ./dist/sub2
  # This workflow contains a single job called "build"
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    needs: [build_cd, build_dist_sub1, build_dist_sub2]
    steps:
      - uses: actions/checkout@v3

      - name: download cd
        uses: actions/download-artifact@v2
        with:
          name: artifact-cd
          path: cd-test.zip

      - name: Extract cd-test
        run: |
          Expand-Archive -Path "./cd-test.zip" -DestinationPath "./"

      - name: download sub1
        uses: actions/download-artifact@v2
        with:
          name: artifact-dist-sub1
          path: dist-test/sub1
      - name: download sub2
        uses: actions/download-artifact@v2
        with:
          name: artifact-dist-sub2
          path: dist-test/sub2
      - name: create destination folder and copy
        run: |
          mkdir space
          Copy-Item -Path .\cd-test -Destination ./space -Recurse -Force
          Copy-Item -Path .\dist-test -Destination ./space -Recurse -Force

      - uses: vimtor/action-zip@v1.1
        with:
          recursive: false
          files: space/
          dest: result.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
