# This is a basic workflow to help you get started with Actions
name: action-demo
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: create destination folder and copy
        run: |
          mkdir space
          Copy-Item -Path .\cd -Destination ./space -Recurse -Force
          Copy-Item -Path .\dist -Destination ./space -Recurse -Force

      - uses: vimtor/action-zip@v1.1
        with:
          recursive: false
          files: space/
          dest: result.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
