# This is a basic workflow to help you get started with Actions
name: action-demo
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  initialize-code:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/steup-node@v3
        with:
          node-version: "18.x"

  build_cd:
    runs-on: windows-latest
    needs: initialize-code
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-cd
          path: ./cd
      - name: Print Node version
        run: |
          node -v

  build_dist:
    runs-on: windows-latest
    needs: initialize-code
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-dist
          path: ./dist
  # This workflow contains a single job called "build"
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    needs: [build_cd, build_dist]
    steps:
      - uses: actions/checkout@v3

      - name: download cd
        uses: actions/download-artifact@v2
        with:
          name: artifact-cd
          path: cd-test
      - name: download infra
        uses: actions/download-artifact@v2
        with:
          name: artifact-dist
          path: dist-test
      - name: create destination folder and copy
        run: |
          mkdir space
          Copy-Item -Path .\cd-test -Destination ./space -Recurse -Force
          Copy-Item -Path .\dist-test -Destination ./space -Recurse -Force

      - uses: vimtor/action-zip@v1.1
        with:
          recursive: false
          files: space/
          dest: result.zip

      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
